"""Utilities for managing NVDA sleep mode for SARA."""

from __future__ import annotations

import atexit
import json
import logging
import os
import time
from pathlib import Path

from sara.core.env import is_e2e_mode
from sara.ui import speech

logger = logging.getLogger(__name__)

_MODULE_FILENAMES = ("python.py", "sara.py", "SARA.py")
_TARGET_FILE = "nvda_sleep_targets.json"
_PLAY_NEXT_SIGNAL_FILE = "nvda_play_next_signal.txt"


def ensure_nvda_sleep_mode() -> None:
    """Ensure NVDA loads an app module that keeps it in sleep mode for this process."""

    if is_e2e_mode():
        logger.info("SARA_E2E enabled – skipping NVDA sleep module install")
        return

    appdata = os.environ.get("APPDATA")
    if not appdata:
        return

    base_path = Path(appdata)
    config_dir = None
    for candidate in ("NVDA", "nvda"):
        cand_path = base_path / candidate
        if cand_path.exists():
            config_dir = cand_path
            break
    if config_dir is None:
        config_dir = base_path / "NVDA"

    nvda_app_modules = config_dir / "appModules"
    nvda_app_modules.mkdir(parents=True, exist_ok=True)
    init_path = nvda_app_modules / "__init__.py"
    if not init_path.exists():
        try:
            init_path.write_text("", encoding="utf-8")
        except OSError as exc:
            logger.warning("Failed to create NVDA appModules __init__: %s", exc)
    package_dir = nvda_app_modules / "python"
    if package_dir.exists():
        try:
            for child in package_dir.glob("*"):
                child.unlink(missing_ok=True)
            package_dir.rmdir()
        except OSError:
            pass

    module_body = (
        '"""Auto-generated by SARA to keep NVDA silent for SARA instances."""\n'
        "import json\n"
        "import os\n"
        "from pathlib import Path\n"
        "import logHandler\n"
        "from appModuleHandler import AppModule\n\n"
        "_TARGET = Path(os.environ.get('APPDATA') or '') / 'SARA' / 'nvda_sleep_targets.json'\n"
        "log = logHandler.getLogger(__name__)\n\n"
        "class AppModule(AppModule):\n"
        "    sleepMode = False\n\n"
        "    def __init__(self, *args, **kwargs):\n"
        "        super().__init__(*args, **kwargs)\n"
        "        self.sleepMode = self._should_sleep()\n"
        "        self._log_state('init')\n\n"
        "    def event_foreground(self, obj, nextHandler):\n"
        "        self.sleepMode = self._should_sleep()\n"
        "        self._log_state('foreground')\n"
        "        if self.sleepMode:\n"
        "            return\n"
        "        super().event_foreground(obj, nextHandler)\n\n"
        "    def _should_sleep(self):\n"
        "        try:\n"
        "            data = json.loads(_TARGET.read_text(encoding='utf-8'))\n"
        "        except Exception:\n"
        "            return False\n"
        "        pids = data.get('pids', [])\n"
        "        return self.processID in pids\n\n"
        "    def _log_state(self, source):\n"
        "        try:\n"
        "            log.info('SARA sleep module %s: pid=%s sleepMode=%s', source, self.processID, self.sleepMode)\n"
        "        except Exception:\n"
        "            pass\n"
    )

    notified = False
    for filename in _MODULE_FILENAMES:
        module_path = nvda_app_modules / filename
        try:
            existing = module_path.read_text(encoding="utf-8") if module_path.exists() else None
            if existing != module_body:
                module_path.write_text(module_body, encoding="utf-8")
                logger.info("Installed/updated NVDA sleep app module at %s", module_path)
                if not notified:
                    speech.speak_text("NVDA sleep module updated. Restart NVDA to apply.")
                    notified = True
        except OSError as exc:
            logger.warning("Failed to create NVDA sleep module %s: %s", filename, exc)

    SaraSleepRegistry(appdata).register_process()


def notify_nvda_play_next() -> None:
    """Signal NVDA add-on that Play Next has been triggered to keep speech silent."""

    appdata = os.environ.get("APPDATA")
    if not appdata:
        return
    try:
        base = Path(appdata) / "SARA"
        base.mkdir(parents=True, exist_ok=True)
        signal_path = base / _PLAY_NEXT_SIGNAL_FILE
        now = str(time.time())
        signal_path.write_text(now, encoding="utf-8")
        logger.info("NVDA play-next signal updated at %s", now)
    except OSError as exc:
        logger.warning("Failed to update NVDA play-next signal: %s", exc)


class SaraSleepRegistry:
    """Maintains a list of SARA process IDs that should trigger NVDA sleep mode."""

    def __init__(self, appdata: str) -> None:
        self._file = Path(appdata) / "SARA"
        self._file.mkdir(parents=True, exist_ok=True)
        self._file = self._file / _TARGET_FILE
        self._pid = os.getpid()
        atexit.register(self.unregister_process)

    def register_process(self) -> None:
        data = self._load()
        pids = set(data.get("pids", []))
        if self._pid not in pids:
            pids.add(self._pid)
            self._save({"pids": sorted(pids)})

    def unregister_process(self) -> None:
        data = self._load()
        pids = set(data.get("pids", []))
        if self._pid in pids:
            pids.remove(self._pid)
            self._save({"pids": sorted(pids)})

    def _load(self) -> dict:
        try:
            return json.loads(self._file.read_text(encoding="utf-8"))
        except OSError:
            return {}
        except json.JSONDecodeError:
            logger.warning("Failed to parse NVDA sleep registry file")
            return {}

    def _save(self, data: dict) -> None:
        try:
            self._file.write_text(json.dumps(data), encoding="utf-8")
        except OSError as exc:
            logger.warning("Failed to update NVDA sleep registry: %s", exc)


__all__ = [
    "SaraSleepRegistry",
    "ensure_nvda_sleep_mode",
    "notify_nvda_play_next",
]

